### ISSUE TITLE
"bfd requires flen 8, but target has flen 0"

### ISSUE THREAD

**Issue by JANlittle** [niklaus520/RISCVDockerEnv#1] opened 2021-04-01 14:56 UTC
Thanks for your docker, sir! But I have encountered some questions I can't solve, can you help me?
I use the `Dockerfile.ctf`, and follow the guide right(maybe), but when I use `target remote 127.0.0.1:1234`, the gdb said:`bfd requires flen 8, but target has flen 0`
My ELF is 64bit, and my OS is Ubuntu18.04. I don't know how to deal with this error, can you give me some advice?

**Comment by zer0pwned** [comment] 2021-04-02 04:58
Hey, glad my docker file can help! 

As far as I know that complain message normally is related with floating point emulation issue on qemu. While I'm investigating how to add FPU support on qemu/whether that is truly the cause of this issue, do you mind also provide bit more information regarding your target ELF file? For example, what is your step to debug your ELF file? Did you build the docker image locally or just pull it from Docker hub?

**Comment by JANlittle** [comment] 2021-04-02 14:22
> 
> 
> Hey, glad my docker file can help!
> 
> As far as I know that complain message normally is related with floating point emulation issue on qemu. While I'm investigating how to add FPU support on qemu/whether that is truly the cause of this issue, do you mind also provide bit more information regarding your target ELF file? For example, what is your step to debug your ELF file? Did you build the docker image locally or just pull it from Docker hub?

Well, thanks you can reply me! And I am glad to share more information:

1. First, I directly pull the docker image from Docker hub by the command: `docker run --name "riscv-toolchain-ctf" -it pwn2de4d/riscv-toolchain-ctf:latest`
2. And then, I copy my target ELF file in image and `file` it:
   `root@5c2464e667f4:~# file main
main: ELF 64-bit LSB executable, UCB RISC-V, version 1 (SYSV), statically linked, for GNU/Linux 4.15.0, BuildID[sha1]=c54b93fd63fcb530ed539bd25e4322a08324b0b7, stripped`
3. Next, I using the following commend: 
   `qemu-system-riscv64 -nographic -machine sifive_e -kernel /root/main -gdb tcp::1234`
   `/opt/riscv-binutils-gdb/bin/riscv64-unknown-elf-gdb -f /root/main`
4. Finally, the gdb tell me a terrible error:
    `gef➤  file main
Reading symbols from main...
(No debugging symbols found in main)
gef➤  target remote 127.0.0.1:1234
Remote debugging using 127.0.0.1:1234
bfd requires flen 8, but target has flen 0`

Here is the whole step I debug my ELF, I hope these can be useful. : )

**Comment by zer0pwned** [comment] 2021-04-02 23:23
hey I did a bit of investigation and I noticed that the current compiled qemu support the following machine and cpu.

```
root@6dc19f84b054:~# qemu-system-riscv64 -cpu help
any
rv64
rv64gcsu-v1.10.0
rv64gcsu-v1.9.1
rv64imacu-nommu
sifive-e51
sifive-u54
root@6dc19f84b054:~# qemu-system-riscv64 -machine help
Supported machines are:
none                 empty machine
sifive_e             RISC-V Board compatible with SiFive E SDK
sifive_u             RISC-V Board compatible with SiFive U SDK
spike                RISC-V Spike Board (default)
spike_v1.10          RISC-V Spike Board (Privileged ISA v1.10)
spike_v1.9.1         RISC-V Spike Board (Privileged ISA v1.9.1)
virt                 RISC-V VirtIO board
```

Do you mind to run `qemu-system-riscv64 -nographic -machine sifive_e -cpu sifive-u54 -kernel /root/main -s -S` real quick and dial into `127.0.0.1:1234` with your gdb and see if it works? 

I briefly went through the `target` and `hw` folder of qemu and I believe they do have floating point unit support. You can check this [file](https://github.com/qemu/qemu/blob/266469947161aa10b1d36843580d369d5aa38589/target/riscv/fpu_helper.c#L41) to confirm.

Also remember to use `-S` option when you issue the qemu command. The `-S` command freeze CPU at startup. QEMU defaults to starting the guest without waiting for gdb to connect so just in case your main file does not have a while loop to wait for you you should freeze it and wait for your gdb to dial in. 

The `-s` option is equivalent to your `-gdb tcp::1234` so you can either keep your way or simply put it as `-s`.

Let me know if this can work for you.

**Comment by zer0pwned** [comment] 2021-04-03 00:42
Can you also execute `/opt/riscv-binutils-gdb/bin/riscv64-unknown-elf-readelf -h /root/main` in your docker? I want to check your ELF Flags which might also be helpful.

```
root@6dc19f84b054:~# /opt/riscv-binutils-gdb/bin/riscv64-unknown-elf-readelf -h qual.elf 
ELF Header:
  Magic:   7f 45 4c 46 01 01 01 00 00 00 00 00 00 00 00 00 
  Class:                             ELF32
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              EXEC (Executable file)
  Machine:                           RISC-V
  Version:                           0x1
  Entry point address:               0x20400000
  Start of program headers:          52 (bytes into file)
  Start of section headers:          40600 (bytes into file)
  Flags:                             0x1, RVC, soft-float ABI
  Size of this header:               52 (bytes)
  Size of program headers:           32 (bytes)
  Number of program headers:         5
  Size of section headers:           40 (bytes)
  Number of section headers:         14
  Section header string table index: 13
```

**Comment by JANlittle** [comment] 2021-04-03 01:54
Here is my ELF Flags:
`root@05c3dbc99989:~# /opt/riscv-binutils-gdb/bin/riscv64-unknown-elf-readelf -h /root/main
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00 
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              EXEC (Executable file)
  Machine:                           RISC-V
  Version:                           0x1
  Entry point address:               0x101c0
  Start of program headers:          64 (bytes into file)
  Start of section headers:          384184 (bytes into file)
  Flags:                             0x5, RVC, double-float ABI
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         5
  Size of section headers:           64 (bytes)
  Number of section headers:         27
  Section header string table index: 26
`
Next I execute `qemu-system-riscv64 -nographic -machine sifive_e -cpu sifive-u54 -kernel /root/main -gdb tcp::1234 -S` and `/opt/riscv-binutils-gdb/bin/riscv64-unknown-elf-gdb -f /root/main`, but it seems not effective...
`gef➤  target remote 127.0.0.1:1234
Remote debugging using 127.0.0.1:1234
bfd requires flen 8, but target has flen 0
`

**Comment by zer0pwned** [comment] 2021-04-03 01:55
If `qemu-system-riscv64 -nographic -machine sifive_e -cpu sifive-u54 -kernel /root/main -s -S` still does not work. Try to run a new docker image `docker run --name "riscv-toolchain-ctf-gdb8.1" -it pwn2de4d/riscv-toolchain-ctf:gdb8.1`. 

Based on this [discussion](https://bugs.gentoo.org/689374) the newer version riscv gdb requires certain kernel support (after 4.20) to address the h/w float abi, which can also be verified over [here](https://sourceware.org/legacy-ml/gdb-cvs/2019-10/msg00134.html). 

I assume your binary file does not actually do something related with floating point and it just happens to be compiled with lp64d ABI. Technically you should be able to switch the target profile on gdb but I never actually did that before so I'm not sure how to do that.

**Comment by JANlittle** [comment] 2021-04-03 01:58
Here is my ELF Flags:
```
root@05c3dbc99989:~# /opt/riscv-binutils-gdb/bin/riscv64-unknown-elf-readelf -h /root/main
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00 
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              EXEC (Executable file)
  Machine:                           RISC-V
  Version:                           0x1
  Entry point address:               0x101c0
  Start of program headers:          64 (bytes into file)
  Start of section headers:          384184 (bytes into file)
  Flags:                             0x5, RVC, double-float ABI
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         5
  Size of section headers:           64 (bytes)
  Number of section headers:         27
  Section header string table index: 26
```

Next I execute `qemu-system-riscv64 -nographic -machine sifive_e -cpu sifive-u54 -kernel /root/main -gdb tcp::1234 -S` and `/opt/riscv-binutils-gdb/bin/riscv64-unknown-elf-gdb -f /root/main`, but it seems not effective...

```
gef➤ target remote 127.0.0.1:1234 
Remote debugging using 127.0.0.1:1234 
bfd requires flen 8, but target has flen 0
```

**Comment by zer0pwned** [comment] 2021-04-03 02:15
Yeah your flags show that your elf was compiled with `double-float ABI`. I think this is the main issue. Try the gdb8.1 tag docker image and I hope it works for you.

**Comment by JANlittle** [comment] 2021-04-03 12:56
Your advice seems helpful! But it still have some strange errors: 

```
gef➤  set arch riscv:rv64  
The target architecture is assumed to be riscv:rv64
gef➤  target remote 127.0.0.1:1234
Remote debugging using 127.0.0.1:1234
warning: Target-supplied registers are not supported by the current architecture

[ Legend: Modified register | Code | Heap | Stack | String ]
───────────────────────────────────────────────────────────────── registers ────
$zero: 0x0000000000000000  →  0x0000000000000000  →  [loop detected]
$ra  : 0x0000000000000000  →  0x0000000000000000  →  [loop detected]
$sp  : 0x0000000000000000  →  0x0000000000000000  →  [loop detected]
$gp  : 0x0000000000000000  →  0x0000000000000000  →  [loop detected]
$tp  : 0x0000000000000000  →  0x0000000000000000  →  [loop detected]
$t0  : 0x0000000020400000  →  0x0000000000000000  →  0x0000000000000000  →  [loop detected]
$t1  : 0x0000000000000000  →  0x0000000000000000  →  [loop detected]
$t2  : 0x0000000000000000  →  0x0000000000000000  →  [loop detected]
$fp  : 0x0000000000000000  →  0x0000000000000000  →  [loop detected]
$s1  : 0x0000000000000000  →  0x0000000000000000  →  [loop detected]
$a0  : 0x0000000000000000  →  0x0000000000000000  →  [loop detected]
$a1  : 0x0000000000000000  →  0x0000000000000000  →  [loop detected]
$a2  : 0x0000000000000000  →  0x0000000000000000  →  [loop detected]
$a3  : 0x0000000000000000  →  0x0000000000000000  →  [loop detected]
$a4  : 0x0000000000000000  →  0x0000000000000000  →  [loop detected]
$a5  : 0x0000000000000000  →  0x0000000000000000  →  [loop detected]
$a6  : 0x0000000000000000  →  0x0000000000000000  →  [loop detected]
$a7  : 0x0000000000000000  →  0x0000000000000000  →  [loop detected]
$s2  : 0x0000000000000000  →  0x0000000000000000  →  [loop detected]
$s3  : 0x0000000000000000  →  0x0000000000000000  →  [loop detected]
$s4  : 0x0000000000000000  →  0x0000000000000000  →  [loop detected]
$s5  : 0x0000000000000000  →  0x0000000000000000  →  [loop detected]
$s6  : 0x0000000000000000  →  0x0000000000000000  →  [loop detected]
$s7  : 0x0000000000000000  →  0x0000000000000000  →  [loop detected]
$s8  : 0x0000000000000000  →  0x0000000000000000  →  [loop detected]
$s9  : 0x0000000000000000  →  0x0000000000000000  →  [loop detected]
$s10 : 0x0000000000000000  →  0x0000000000000000  →  [loop detected]
$s11 : 0x0000000000000000  →  0x0000000000000000  →  [loop detected]
$t3  : 0x0000000000000000  →  0x0000000000000000  →  [loop detected]
$t4  : 0x0000000000000000  →  0x0000000000000000  →  [loop detected]
$t5  : 0x0000000000000000  →  0x0000000000000000  →  [loop detected]
$t6  : 0x0000000000000000  →  0x0000000000000000  →  [loop detected]
───────────────────────────────────────────────────────────────────── stack ────
0x0000000000000000│+0x0000: 0x0000000000000000  →  [loop detected]	 ← $zero, $ra, $sp, $gp, $tp, $t1, $t2, $fp, $s1, $a0, $a1, $a2, $a3, $a4, $a5, $a6, $a7, $s2, $s3, $s4, $s5, $s6, $s7, $s8, $s9, $s10, $s11, $t3, $t4, $t5, $t6
0x0000000000000008│+0x0008: 0x0000000000000000  →  0x0000000000000000  →  [loop detected]
0x0000000000000010│+0x0010: 0x0000000000000000  →  0x0000000000000000  →  [loop detected]
0x0000000000000018│+0x0018: 0x0000000000000000  →  0x0000000000000000  →  [loop detected]
0x0000000000000020│+0x0020: 0x0000000000000000  →  0x0000000000000000  →  [loop detected]
0x0000000000000028│+0x0028: 0x0000000000000000  →  0x0000000000000000  →  [loop detected]
0x0000000000000030│+0x0030: 0x0000000000000000  →  0x0000000000000000  →  [loop detected]
0x0000000000000038│+0x0038: 0x0000000000000000  →  0x0000000000000000  →  [loop detected]
────────────────────────────────────────────────────────── code:riscv:RISCV ────
   0xfffffffffffffff4                  unimp  
   0xfffffffffffffff6                  unimp  
   0xfffffffffffffff8                  unimp  
 →        0x0                  unimp  
          0x2                  unimp  
          0x4                  unimp  
          0x6                  unimp  
          0x8                  unimp  
          0xa                  unimp  
─────────────────────────────────────────────────────────────────── threads ────
[#0] Id 1, stopped 0x0 in ?? (), reason: SIGTRAP
───────────────────────────────────────────────────────────────────── trace ────
[#0] 0x0 → unimp 
────────────────────────────────────────────────────────────────────────────────
0x0000000000000000 in ?? ()
gef➤  run
The "remote" target does not support "run".  Try "help target" or "continue".
gef➤  continue 
Continuing.

```

Finally the shell have not any respond...

But the ELF can be execute actually: 

```
root@39102e2e5a17:~# /opt/qemu-riscv-static/bin/qemu-riscv64 ./main
Input the flag: awd51as56d165as1d56
You are wrong ._.
```

Is there a mistake in my operation?

**Comment by zer0pwned** [comment] 2021-04-03 16:49
Wait, so your ELF file can directly runs with qemu-user. 

Can you simply do `/opt/qemu-riscv-static/bin/qemu-riscv64 ./main -g 1234` and use gdb to dail into this port? The `unimp` in your gef output suggests that your qemu-system did not successfully load image into memory (could be wrong cpu/machine).

**Comment by JANlittle** [comment] 2021-04-03 17:11
The situation seems not good: 

```
root@3492aa7da74a:~# /opt/qemu-riscv-static/bin/qemu-riscv64 ./main -g 1234
Input the flag: 

```

```
gef➤  target remote 127.0.0.1:1234 
127.0.0.1:1234: Connection timed out.
```

Other port is the same situation.

**Comment by zer0pwned** [comment] 2021-04-03 17:27
sorry, my bad. `/opt/qemu-riscv-static/bin/qemu-riscv64 -g 1234 ./main`. `qemu-riscv64` needs to take the options first.

**Comment by zer0pwned** [comment] 2021-04-03 18:20
okay I downloaded one CTF riscv64 challenge file from [here](https://github.com/phra/metasploit2020-five-of-hearts/blob/545f14f8ff113802175a854a65e6ad6795ef44e6/binary). The compilation flags are almost identical to yours. I believe it should work now with the gdb8.1 docker image.

![Snipaste_2021-04-03_14-16-46](https://user-images.githubusercontent.com/3125626/113487662-64594580-9487-11eb-8060-9004b5eb01f8.png)

**Comment by JANlittle** [comment] 2021-04-04 01:55
Great!!! It thinks can be work correctly! 

```
root@5979950fa525:~# /opt/qemu-riscv-static/bin/qemu-riscv64 -g 1234 ./main
Input the flag: 
```

```
gef➤  target remote 127.0.0.1:1234 
Remote debugging using 127.0.0.1:1234
warning: Target-supplied registers are not supported by the current architecture

[ Legend: Modified register | Code | Heap | Stack | String ]
───────────────────────────────────────────────────────────────── registers ────
$zero: 0x0000000000000000  →  0x0000000000000000
$ra  : 0x0000000000000000  →  0x0000000000000000
$sp  : 0x0000004000800760  →  0x0000000000000001  →  0x0000000000000001
$gp  : 0x0000000000000000  →  0x0000000000000000
$tp  : 0x0000000000000000  →  0x0000000000000000
$t0  : 0x0000000000000000  →  0x0000000000000000
$t1  : 0x0000000000000000  →  0x0000000000000000
$t2  : 0x0000000000000000  →  0x0000000000000000
$fp  : 0x0000000000000000  →  0x0000000000000000
$s1  : 0x0000000000000000  →  0x0000000000000000
$a0  : 0x0000000000000000  →  0x0000000000000000
$a1  : 0x0000000000000000  →  0x0000000000000000
$a2  : 0x0000000000000000  →  0x0000000000000000
$a3  : 0x0000000000000000  →  0x0000000000000000
$a4  : 0x0000000000000000  →  0x0000000000000000
$a5  : 0x0000000000000000  →  0x0000000000000000
$a6  : 0x0000000000000000  →  0x0000000000000000
$a7  : 0x0000000000000000  →  0x0000000000000000
$s2  : 0x0000000000000000  →  0x0000000000000000
$s3  : 0x0000000000000000  →  0x0000000000000000
$s4  : 0x0000000000000000  →  0x0000000000000000
$s5  : 0x0000000000000000  →  0x0000000000000000
$s6  : 0x0000000000000000  →  0x0000000000000000
$s7  : 0x0000000000000000  →  0x0000000000000000
$s8  : 0x0000000000000000  →  0x0000000000000000
$s9  : 0x0000000000000000  →  0x0000000000000000
$s10 : 0x0000000000000000  →  0x0000000000000000
$s11 : 0x0000000000000000  →  0x0000000000000000
$t3  : 0x0000000000000000  →  0x0000000000000000
$t4  : 0x0000000000000000  →  0x0000000000000000
$t5  : 0x0000000000000000  →  0x0000000000000000
$t6  : 0x0000000000000000  →  0x0000000000000000
───────────────────────────────────────────────────────────────────── stack ────
0x0000004000800760│+0x0000: 0x0000000000000001  →  0x0000000000000001	 ← $sp
0x0000004000800768│+0x0008: 0x0000004000800901  →  0x5f006e69616d2f2e  →  0x5f006e69616d2f2e
0x0000004000800770│+0x0010: 0x0000000000000000  →  0x0000000000000000
0x0000004000800778│+0x0018: 0x0000004000800908  →  0x712f74706f2f3d5f  →  0x712f74706f2f3d5f
0x0000004000800780│+0x0020: 0x0000004000800932  →  0x4e45504f5353454c  →  0x4e45504f5353454c
0x0000004000800788│+0x0028: 0x0000004000800952  →  0x73752f3d48544150  →  0x73752f3d48544150
0x0000004000800790│+0x0030: 0x0000004000800994  →  0x00313d4c564c4853  →  0x00313d4c564c4853
0x0000004000800798│+0x0038: 0x000000400080099c  →  0x6574783d4d524554  →  0x6574783d4d524554
────────────────────────────────────────────────────────── code:riscv:RISCV ────
      0x101b4                  jal    ra, 0x21dfc
      0x101b8                  ld     a0, 1664(gp)
      0x101bc                  j      0x44f90
 →    0x101c0                  jal    ra, 0x101ec
      0x101c4                  mv     a5, a0
      0x101c6                  auipc  a0, 0x0
      0x101ca                  addi   a0, a0, 570
      0x101ce                  ld     a1, 0(sp)
      0x101d0                  addi   a2, sp, 8
─────────────────────────────────────────────────────────────────── threads ────
[#0] Id 1, stopped 0x101c0 in ?? (), reason: SIGTRAP
───────────────────────────────────────────────────────────────────── trace ────
[#0] 0x101c0 → jal ra, 0x101ec
────────────────────────────────────────────────────────────────────────────────
0x00000000000101c0 in ?? ()
gef➤  continue
Continuing.


```

(But why the qemu-system can't work well...

**Comment by zer0pwned** [comment] 2021-04-04 02:39
qemu-system is used to do a [full system emulation](https://qemu-project.gitlab.io/qemu/system/index.html), which is opposed to qemu-user. 

In order to run your ELF with qemu-system, you need to first supply an appropriate system image to allow your ELF runs on. In your case, this system image should be Linux kernel/os. You should follow these [instructions](https://risc-v-getting-started-guide.readthedocs.io/en/latest/linux-qemu.html) to build your Linux kernel image and load a full Linux system with qemu-system. 

The example I use in README works for ELF which is compiled for another platform, SiFive. The SiFive/sifive_e system image which comes with qemu-system might not setup floating point unit. 

I'm going to close this issue but feel free to reopen it if you have more issues in your case. Good luck and enjoy your CTF.

**Closed as completed by zer0pwned** 2021-04-04 02:39 UTC
